### ISSUE TITLE
Reference LOOKUP not working

### ISSUE THREAD

**Issue by blcakcatming** [keikai/dev-ref#4]
upload excel but reference LOOKUP not working
version: keikai-app-5.10.0-Eval

![image](https://user-images.githubusercontent.com/101324268/187406618-81633abf-98ae-45ee-a33f-49d1d3bb6cb4.png)

**Comment by hawkchen** [comment]
according to [LOOKUP doc](https://support.microsoft.com/en-us/office/lookup-function-446d94af-663b-451d-8251-369d5e3864cb), the 2nd argument is a lookup_vector, a range. But yours is `0/((B2:M2=C151)*(B4:M4=B151))` which looks like a number, not a range. I think that argument might be the root cause of the error.

**Comment by blcakcatming** [comment]
It is two ranges, `B2:M2` and `B4:M4`, it can work well in Windows Excel

**Comment by hawkchen** [comment]
But your screenshot shows that the 2nd argument is `0/((B2:M2=C151)*(B4:M4=B151))` which is not range. Could show me the formula you mentioned or a sample xlsx file?

**Comment by blcakcatming** [comment]
[demo.xlsx](https://github.com/keikai/dev-ref/files/9673210/demo.xlsx)
Please look at this file  `J151:O151`

**Comment by hawkchen** [comment]
I see. you want to match 2 criteria in LOOKUP like https://www.microsoft.com/en-us/microsoft-365/blog/2012/04/26/using-multiple-criteria-in-excel-lookup-formulas/
But keikai doesn't support the syntax like `B2:M2=C151`. We need to find an alternative.

**Comment by blcakcatming** [comment]
I'm looking for another way out. Anyway, thank you for your reply
